services:
  react-app:
    build: ./fe
    ports:
      - "3000:5173"
    environment:
      - NODE_ENV=production
    networks:
      - app-network

  flask-app:
    build: ./be-new
    ports: 
      - "8080:8080"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
